Skeleton 5
ae"ElaborateEnv"i1aдҐS"gp1c"ELABORATE_ENV_STRUCTS"jh6egp1€Cbegp2дҐControl"d"Elaborate"ж0beзр±дҐAst"d7aдҐBasid"gp1€Б'aдҐFctid"gp1€Б6CaдҐField"gp2дҐSortedRecord"€ВбдҐStrid"зр±€В$aдҐLongvid"gp1€В3aдҐLongstrid"gp1€ГaдҐLongtycon"gp1€ГCaдҐPriority"gp1€Г+aдҐSigid"gp1€Г=a€Вgp1€В€В#бдҐSymbol"зр±€ДNbeзр±дҐCoreML"d7aдҐCon"gp1€Д:aдҐDec"gp1€ЕCaдҐExp"gp1€ЕaдҐPat"gp1€Е"бдҐTycon"зр±€Е/aдҐTyvar"gp1€Е>aдҐVar"gp1€ЖNbе€Е7d3бдҐAdmitsEquality"зр±€Ж"бдҐKind"зр±€Ж:€Дbegp±дҐTypeEnv"d2бдҐScheme"зр±€ЗaдҐType"зр±€З,Cf6€БC€Д:€ЖдҐList"дҐVector"€Г+NaдҐDecs"jh1a€Д.€Д+gp1e€Иa€Е/h2€Жf€Зa€З,h4е€З3везр±дҐLayout"€Бf€Йbd2€Йf6дҐOption"C€И€В€Е/€В€Ж"N€Бa€Зh2е€З%f2€З,€ЙCaдҐScope"h1ad"Unique"jи0gp1e"UniqueId"aдҐUses"к€К-€К-aдҐClass"€К-aдҐVid"h2bd2€Йf7€Д:€ЖC€Й'€З€И€Г+€ЙN€Бf1€ЛaдҐTypeStr"h8€Ж!€Ж9€Е.CaдҐCons"h1b€Йf2€Б€Зb€Йf3€М €З€Е/f4€З€Е/€Ж"€Йb€Йf6€БC€М €З,€З€И€Е/Nf3€Ж:€З,€ЗNCbезр±€М	a€М зр±€М aдҐInterface"jh2a€Б€Бad"EnvTypeStr"€Н;gp1e€Оbезр±€Оd3aдҐFlexibleTycon"gp1€ПбдҐStatus"зр±€ПaдҐTyconMap"gp1€П,f9€БдҐInt"d"Ref"€ЛC€И€Ж:€ИдҐUnit"€К>C€Й'дҐRegion"d"BinarySearch"€ЗдҐString"C€Д€П,€З€М	дҐQuickSort"CдҐArray"€Б'€Л€Б6d"MLton"C€К€Г=€В$дҐTrace"€Е/C€Ж"€Бd"Counter"дҐPropertyList"€ЙNa€Оh5CaдҐEcons"€ОaдҐEscheme"€З%aдҐEtype"€З3aдҐEtypeStr"€Н;€О;Cf4€Й'€М	€Е/€У'b€Йf3€М	дҐError"€У'f8€Д:d"Exn"€М C€З,€К>€Й'€З€ИC€У€У€У€Е/€У'Nb€Жf1€У'f2€П€У'Ca€Е/h1€Жa€З,h2€Йf5C€Ж:€З,€И€У€Е/Na€Зh2€К
f3€З,€З€Уa€М h2e€Оf3€З€И€Уa€М	h2€Н:f5C€М €З€М	€Е/€У'NNCa€Пh1e€П%aдҐTime"€ЛaдҐInfo"€К-aдҐStructure"h2b€Йf6€БC€Д:€Л€М €Ч€Ж:C€И€З,€К>€Й'€ЗC€И€М	€С'€Ф€Г=C€В$€Е>€Ж"€О€ЙNf€В.aдҐFunctorClosure"€К-CaдҐBasis"€К-aдҐValues"€К-aдҐNameSpace"€К-aдҐAll"€К-b€Йf1€РCf8€Ъ€Б€ЛC€Ч€И€Ч€К>d"Pretty"C€Р)€Ч)€П€Д€Щ(C€П,€Щ5€М	€С€ПC€С'€Б'€Л€Ф€Б6C€К€Г=€В$€Т
€Е/CдҐProperty"€Д.€О€Т&€ЙNbd2€Йf9€Ч)€Щ€С'€Б'C€Б6€Г=€В$€Ы:€ОN€Бf6€ИC€З,€К>€Й'€Р)€Ч)C€З€Д€Щ(€Щ5€ЩC€С€С'€Л€К€ЙNbd3b€Йf2€Л€Бf6d"File"C€И€Р)€С€С'€БNb€Йf5C€И€Р)€С€Лd"SourcePos"N€Бf7€Б€Д:C€Л€М €К>€Й'€ЗC€И€Щ5€Л€Б€ЙNC€Й
f8€Б€И€Р)C€Ч)€В$€Г€Б€ЙNaдҐPeekResult"€К-€Й
f9€Б€Д:€Ж€ЛC€М €И€Ч€И€ЧC€Р€К>€Й'€Р)€Ч)C€З€Щ(€И€Щ5€†C€Щ€З€М	€С'€ЩC€Л€Ф€К€Т
d"Promise"√€Ы:€О€Б€Т&€ЙNCad"ExtendUses"€К-bd8bd2b€Йж±€Бf4€З,€З€И€Е>f2€З,€Зf9€Б€М €И€РC€З€И€В$€Т
€ЙNbd2b€Йf4€Б€И€И€Бf2€Б€И€БCf3€Ж:€М	€Ж"bd2€Йf3€Б€М	€Б€Бf2€Ж:€М	bd2€Йf3€Б€Ж:€Б€Бbd2€Йf3€Б€Б€Й€БCf9€Б€Ч€Ж:€З,C€З€И€М	€С'€ФC€В$€Е/€Е>€О€ЙNbbd2bd2€Й€Ґ+f2€Ч€К>f1€С'€Бf1€Чf9€Б€И€Р€Ч)C€З€П,€З€П€С'C€Ф€В$€Т
€Ы:€ОNbd2bd7b€Йf2€В3€Бf€З5C€Й
f1€Иb€Йf4€И€З€И€Е>f5C€Д:€Е€Е€Е"€ЖC€Л€И€П€И€ЙNbd2€Йf5C€Б€Л€П€Б€ЙN€БN€Бf6€БC€Д:€Ж€Л€П€ОNf2€Ч)€Т&f6€ИC€Й'€Ч)€М	€П€ОNNf1€Иf5C€М €И€Ч€И€ЧC€З,€Й'€Ч)€З€Щ(C€И€Щ5€Щ€З€М	C€Ф€К€В$€Т
€Е/€°>aдҐEnv"€К-ad"InterfaceEnv"h2b€О;d3€З€Пa€М	€Н;f6€БC€Ђ
€Ч€И€Ч€К>C€Й'€Р)€П€Д€Щ(C€Щ5€М	€С'€К€В$C€О€Г€Г€Б€ЙNNgp1c"ELABORATE_ENV"